[package]
name = "ghostfoliodata"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
rocket = "0.5.0"
rocket_contrib = "0.4.11"
rocket_codegen = "0.5.0"
diesel = { version = "2.1.0", features = ["postgres"] }
diesel_cli = "2.1.1"
