
x-app-service-template: &main
    build:
      context: .
    image: ghostfoliodata
    volumes:
      - '.:/app'
services:
  app:
    <<: *main
    env_file: ./env.development
    depends_on:
      - db
    ports:
      - 3000:3000
      - 5000:5000
  test:
    <<: *main
    depends_on:
      - db
    env_file: ./env.test

  redis:
    image: redis:7.0.4-alpine
    container_name: ghostfoliodataredis
    ports:
      - 6379:6379

  db:
    build: ./postgres/
    container_name: ghostfoliodatadb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
volumes:
  db_data:
