version: '3.5'
x-app-service-template: &main
    build:
      context: .
    image: ghostfoliodata
    volumes:
      - '.:/app'
services:
  app:
    <<: *main
    env_file: ./env.development
    ports:
      - 3000:3000
      - 5000:5000
  test:
    <<: *main
    env_file: ./env.test

  db:
    build: ./mysql/
    container_name: ghostfoliodatadb
    restart: always
    # volumes:|
    #   - ./data:/var/lib/postgresql/data/
