
x-app-service-template: &main
    build:
      context: .
    image: ghostfoliodata
    volumes:
      - '.:/app'
services:
  app:
    <<: *main
    env_file: ./env.development
    depends_on:
      - db
    ports:
      - 3000:3000
      - 5000:5000
  test:
    <<: *main
    depends_on:
      - db
    env_file: ./env.test

  db:
    build: ./postgres/
    container_name: ghostfoliodatadb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/
